version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
  api:
    image: ink-multisig-squid-shibuya
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: ink-multisig-squid-shibuya
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3000
      - "3000:3000"
    command: ["./wait-for-it.sh", "db:5432", "--", "sqd", "process:prod"]
    depends_on:
      - db